version: '3'

services:
  backend:
    build: .
    ports:
      - '8000:8000'
    command: python manage.py runserver [::]:8000
    volumes:
      - '.:/code'
  tests:
    build: .
    command: ./coverage.sh
    volumes:
    - '.:/code'